### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [Playtika/aerospike-janusgraph-storage-backend#25]
First of all, **thank you** for creating & open-sourcing a new backend for JanusGraph! This is a great contribution to the JanusGraph ecosystem; please consider advertising it (whenever you're ready) on the [janusgraph-users@ list](https://github.com/JanusGraph/janusgraph/#community).

---

Could you please add an explicit `LICENSE` file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

Thanks!

**Comment by vasilievip** [comment]
>please consider advertising it 
Connector is now being tested in-house on "master record for players accounts" project. Once this project will be live in production we will send email to the group.

**Comment by vasilievip** [comment]
>Could you please add an explicit

\+

**Comment by porunov** [comment]
> Connector is now being tested in-house on "master record for players accounts" project. Once this project will be live in production we will send email to the group.

I would like to ask to also add a comment in [this PR](https://github.com/JanusGraph/janusgraph.org/pull/67) when this adapter is production ready. Regards

**Comment by vasilievip** [comment]
Sure

Since you might be wondering whats going on: janus graph in "embedded mode" (this means bundled as library into java service, to support local transactions and repository access pattern) on top of aerospike deployed to production in hidden mode. There is traffic mirroring for online service requests and data migration daemon for bi-directional data sync. Since its sensible component for business, gradual opening will take a while in order to avoid any side effects on players.

Additionally we started development of something like "in-game social graph" between players project which uses janus graph+aerospike as well.  

So, once first project will go live - I'll resolve this ticket.

**Comment by vasilievip** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/janusgraph-users/OC92ovucThw/M8BE_sGcAwAJ

**Comment by mbrukman** [comment]
Additionally, looks like a [`LICENSE`][license] file was added in https://github.com/Playtika/aerospike-janusgraph-storage-backend/commit/444a2ff409d50a5b8b768129586287980e90c8e0 — thanks!

[license]: https://github.com/Playtika/aerospike-janusgraph-storage-backend/blob/7256c20c1855a8854b7d8e935ef63a25b7ea055d/LICENSE
